"""Milestone 4 – PDF Export Generator.

Produces a publication-grade, styled executive assessment report PDF
using ReportLab.
"""
from __future__ import annotations
import io
from typing import Any, Dict

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and print total page numbers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "Prediction AI — Comprehensive Startup Risk Assessment Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer (all pages)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        self.drawString(54, 32, "Confidential • Generated by Prediction AI Intelligence Engine")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_text)
        self.restoreState()


def build_pdf_report(report_data: Dict[str, Any]) -> bytes:
    """Generate a high-quality binary PDF from assessment report data."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    metadata = report_data.get("metadata", {})
    exec_summary = report_data.get("executiveSummary", {})
    risk_assessment = report_data.get("riskAssessment", {})
    swot = report_data.get("swotAnalysis", {})
    competitors_info = report_data.get("competitorIntelligence", {})
    recommendations_info = report_data.get("strategicRecommendations", {})
    action_plan = report_data.get("actionPlan", {})

    startup_name = metadata.get("startupName", "Startup")
    industry = metadata.get("industry", "Technology")
    budget = float(metadata.get("budget") or 0)
    generated_at = metadata.get("generatedAt", "")

    styles = getSampleStyleSheet()
    
    # Custom Palette
    c_primary = colors.HexColor("#1E3A8A")     # Deep Blue
    c_secondary = colors.HexColor("#6B21A8")   # Deep Purple
    c_emerald = colors.HexColor("#047857")     # Emerald
    c_crimson = colors.HexColor("#B91C1C")     # Crimson
    c_dark = colors.HexColor("#0F172A")        # Dark Slate
    c_muted = colors.HexColor("#475569")       # Muted Slate
    c_bg_light = colors.HexColor("#F8FAFC")    # Slate 50
    c_border = colors.HexColor("#CBD5E1")      # Slate 300

    # Custom Typography Styles
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=c_dark,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=c_muted,
        spaceAfter=12,
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=c_primary,
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=c_dark,
    )
    body_bold = ParagraphStyle(
        "BodyBold",
        parent=body_style,
        fontName="Helvetica-Bold",
    )
    badge_style = ParagraphStyle(
        "BadgeStyle",
        parent=body_style,
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=colors.white,
        alignment=1,
    )

    story = []

    # -------------------------------------------------------------------------
    # 1. Header & Cover Banner
    # -------------------------------------------------------------------------
    banner_data = [
        [
            Paragraph(
                f"<font size='13'><b>PREDICTION AI</b></font><br/>"
                f"<font size='8' color='#64748B'>Venture Market Intelligence &amp; Risk Analytics</font>",
                body_style,
            ),
            Paragraph(
                f"<b>Assessment Date:</b> {generated_at}<br/>"
                f"<b>Status:</b> <font color='#047857'><b>Verified Complete</b></font>",
                ParagraphStyle("RightText", parent=body_style, alignment=2),
            ),
        ]
    ]
    t_banner = Table(banner_data, colWidths=[250, 254])
    t_banner.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_banner)
    story.append(HRFlowable(width="100%", thickness=1.5, color=c_primary, spaceBefore=4, spaceAfter=14))

    story.append(Paragraph(f"Startup Risk &amp; Feasibility Assessment: {startup_name}", title_style))
    story.append(Paragraph(
        f"<b>Industry:</b> {industry} &nbsp;|&nbsp; <b>Model:</b> {metadata.get('businessModel', 'N/A')} &nbsp;|&nbsp; "
        f"<b>Allocated Budget:</b> ₹{budget:,.0f} &nbsp;|&nbsp; <b>Target Market:</b> {metadata.get('targetMarket', 'N/A')}",
        subtitle_style,
    ))

    # -------------------------------------------------------------------------
    # 2. Key Metrics Snapshot (KPI Strip)
    # -------------------------------------------------------------------------
    risk_score = exec_summary.get("riskScore", 0)
    succ_prob = exec_summary.get("successProbability", 0)
    feas_score = exec_summary.get("feasibilityScore", 0)
    verdict = exec_summary.get("verdict", "N/A")
    risk_lvl = exec_summary.get("overallRiskLevel", "N/A")

    kpi_data = [
        [
            Paragraph("<font color='#64748B' size='7.5'>OVERALL RISK SCORE</font><br/><font size='14'><b>" + str(risk_score) + "</b>/100</font><br/><font size='7.5' color='#B91C1C'><b>" + risk_lvl + "</b></font>", body_style),
            Paragraph("<font color='#64748B' size='7.5'>SUCCESS PROBABILITY</font><br/><font size='14'><b>" + str(succ_prob) + "%</b></font><br/><font size='7.5' color='#1E3A8A'><b>AI Forecast</b></font>", body_style),
            Paragraph("<font color='#64748B' size='7.5'>FEASIBILITY SCORE</font><br/><font size='14'><b>" + str(feas_score) + "%</b></font><br/><font size='7.5' color='#047857'><b>" + verdict + "</b></font>", body_style),
            Paragraph("<font color='#64748B' size='7.5'>RECOMMENDATIONS</font><br/><font size='14'><b>" + str(len(recommendations_info.get("recommendations", []))) + "</b></font><br/><font size='7.5' color='#6B21A8'><b>Actionable Plays</b></font>", body_style),
        ]
    ]
    t_kpi = Table(kpi_data, colWidths=[126, 126, 126, 126])
    t_kpi.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), c_bg_light),
        ("BOX", (0, 0), (-1, -1), 1, c_border),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(t_kpi)
    story.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 3. Section 1 – Executive Summary
    # -------------------------------------------------------------------------
    story.append(Paragraph("1. Executive Summary", section_heading))
    findings = exec_summary.get("summaryText", [])
    if isinstance(findings, list):
        for f in findings:
            story.append(Paragraph(f"• {f}", body_style))
            story.append(Spacer(1, 2))
    else:
        story.append(Paragraph(str(findings), body_style))
    story.append(Spacer(1, 10))

    # -------------------------------------------------------------------------
    # 4. Section 2 – Risk Assessment & Category Breakdown
    # -------------------------------------------------------------------------
    story.append(Paragraph("2. Risk Assessment Breakdown", section_heading))
    breakdown = risk_assessment.get("breakdown", {})

    risk_table_data = [
        [
            Paragraph("<b>Risk Category</b>", body_bold),
            Paragraph("<b>Score (0-100)</b>", body_bold),
            Paragraph("<b>Impact Level</b>", body_bold),
            Paragraph("<b>Key Mitigation Action</b>", body_bold),
        ],
        [
            Paragraph("Financial Risk", body_style),
            Paragraph(f"{breakdown.get('financialRisk', 50)}%", body_style),
            Paragraph("<font color='#B91C1C'>High</font>" if breakdown.get('financialRisk', 50) >= 60 else "Moderate", body_style),
            Paragraph("Secure seed funding & maintain 12+ mo runway controls", body_style),
        ],
        [
            Paragraph("Competition Risk", body_style),
            Paragraph(f"{breakdown.get('competitionRisk', 50)}%", body_style),
            Paragraph("<font color='#B91C1C'>High</font>" if breakdown.get('competitionRisk', 50) >= 60 else "Moderate", body_style),
            Paragraph("Execute niche beachhead strategy with unique value prop", body_style),
        ],
        [
            Paragraph("Technical Risk", body_style),
            Paragraph(f"{breakdown.get('technicalRisk', 50)}%", body_style),
            Paragraph("<font color='#B91C1C'>High</font>" if breakdown.get('technicalRisk', 50) >= 60 else "Moderate", body_style),
            Paragraph("Develop rapid MVP prototype to de-risk architecture", body_style),
        ],
        [
            Paragraph("Operational Risk", body_style),
            Paragraph(f"{breakdown.get('operationalRisk', 50)}%", body_style),
            Paragraph("Moderate", body_style),
            Paragraph("Automate repetitive workflows and formalize team SLAs", body_style),
        ],
        [
            Paragraph("Market Risk", body_style),
            Paragraph(f"{breakdown.get('marketRisk', 50)}%", body_style),
            Paragraph("Moderate", body_style),
            Paragraph("Continuous user discovery interviews and NPS tracking", body_style),
        ],
    ]
    t_risk = Table(risk_table_data, colWidths=[110, 80, 80, 234])
    t_risk.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ("BOX", (0, 0), (-1, -1), 1, c_border),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t_risk)
    story.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 5. Section 3 – Automated SWOT Matrix
    # -------------------------------------------------------------------------
    story.append(Paragraph("3. SWOT Analysis Matrix", section_heading))
    strengths = swot.get("Strengths", ["Baseline execution"])
    weaknesses = swot.get("Weaknesses", ["Resource constraints"])
    opportunities = swot.get("Opportunities", ["Market expansion"])
    threats = swot.get("Threats", ["Competitive pressure"])

    s_text = "<br/>".join([f"• {item}" for item in strengths])
    w_text = "<br/>".join([f"• {item}" for item in weaknesses])
    o_text = "<br/>".join([f"• {item}" for item in opportunities])
    t_text = "<br/>".join([f"• {item}" for item in threats])

    swot_table_data = [
        [
            Paragraph("<font color='#047857'><b>STRENGTHS (Internal)</b></font><br/>" + s_text, body_style),
            Paragraph("<font color='#B91C1C'><b>WEAKNESSES (Internal)</b></font><br/>" + w_text, body_style),
        ],
        [
            Paragraph("<font color='#1E3A8A'><b>OPPORTUNITIES (External)</b></font><br/>" + o_text, body_style),
            Paragraph("<font color='#D97706'><b>THREATS (External)</b></font><br/>" + t_text, body_style),
        ],
    ]
    t_swot = Table(swot_table_data, colWidths=[252, 252])
    t_swot.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#ECFDF5")),
        ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#FEF2F2")),
        ("BACKGROUND", (0, 1), (0, 1), colors.HexColor("#EFF6FF")),
        ("BACKGROUND", (1, 1), (1, 1), colors.HexColor("#FFFBEB")),
        ("BOX", (0, 0), (-1, -1), 1, c_border),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t_swot)
    story.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 6. Section 4 – Competitor Intelligence & Market Sizing
    # -------------------------------------------------------------------------
    story.append(Paragraph("4. Market Sizing & Competitor Intelligence", section_heading))
    m_data = competitors_info.get("marketData", {})
    comps = competitors_info.get("competitors", [])

    mkt_summary = (
        f"<b>Total Addressable Market (TAM):</b> {m_data.get('tam', 'N/A')} &nbsp;|&nbsp; "
        f"<b>Serviceable Addressable Market (SAM):</b> {m_data.get('sam', 'N/A')} &nbsp;|&nbsp; "
        f"<b>Serviceable Obtainable Market (SOM):</b> {m_data.get('som', 'N/A')} &nbsp;|&nbsp; "
        f"<b>Annual Growth:</b> {m_data.get('growth_rate', 10)}%"
    )
    story.append(Paragraph(mkt_summary, body_style))
    story.append(Spacer(1, 6))

    if comps:
        comp_rows = [
            [
                Paragraph("<b>Competitor</b>", body_bold),
                Paragraph("<b>Market Share</b>", body_bold),
                Paragraph("<b>Est. Revenue</b>", body_bold),
                Paragraph("<b>Growth Rate</b>", body_bold),
            ]
        ]
        for c in comps:
            comp_rows.append([
                Paragraph(c.get("name", "Competitor"), body_style),
                Paragraph(f"{c.get('market_share', 0)}%", body_style),
                Paragraph(str(c.get("revenue", "-")), body_style),
                Paragraph(str(c.get("growth", "-")), body_style),
            ])
        t_comp = Table(comp_rows, colWidths=[150, 110, 120, 124])
        t_comp.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 1, c_border),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(t_comp)
    story.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 7. Section 5 – Strategic Recommendations
    # -------------------------------------------------------------------------
    story.append(Paragraph("5. AI Strategic Recommendations", section_heading))
    recs = recommendations_info.get("recommendations", [])
    if recs:
        rec_rows = [
            [
                Paragraph("<b>Priority</b>", body_bold),
                Paragraph("<b>Recommendation</b>", body_bold),
                Paragraph("<b>Strategic Description &amp; Directives</b>", body_bold),
            ]
        ]
        for r in recs:
            p_color = "#B91C1C" if r.get("priority") == "Critical" else ("#D97706" if r.get("priority") == "High" else "#1E3A8A")
            rec_rows.append([
                Paragraph(f"<font color='{p_color}'><b>{r.get('priority', 'Medium')}</b></font>", body_style),
                Paragraph(f"<b>{r.get('title', 'Action')}</b>", body_style),
                Paragraph(r.get("description", ""), body_style),
            ])
        t_rec = Table(rec_rows, colWidths=[70, 140, 294])
        t_rec.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 1, c_border),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t_rec)
    story.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 8. Section 6 – Phased Action Plan (3-Tier)
    # -------------------------------------------------------------------------
    story.append(Paragraph("6. Phased Implementation Action Plan", section_heading))
    plan_rows = [
        [
            Paragraph("<b>Phase / Timeline</b>", body_bold),
            Paragraph("<b>Action Item</b>", body_bold),
            Paragraph("<b>Description</b>", body_bold),
            Paragraph("<b>Accountability</b>", body_bold),
        ]
    ]
    for phase_key, phase_label in [("immediate", "0 - 30 Days"), ("shortTerm", "1 - 3 Months"), ("longTerm", "3 - 12 Months")]:
        items = action_plan.get(phase_key, [])
        for item in items:
            plan_rows.append([
                Paragraph(f"<b>{phase_label}</b>", body_style),
                Paragraph(item.get("action", ""), body_style),
                Paragraph(item.get("description", ""), body_style),
                Paragraph(item.get("owner", "Team"), body_style),
            ])

    t_plan = Table(plan_rows, colWidths=[90, 130, 204, 80])
    t_plan.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ("BOX", (0, 0), (-1, -1), 1, c_border),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, c_border),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t_plan)

    # Build PDF with dynamic page numbering
    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
